/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 *  ‘***  Class Name: addBookGui
‘***  Class Author: Angelica Jones
‘******************************************************
‘*** Purpose of the class (Why did you write this class?)
‘***: for user to add items/objects/attribute to the books class
* Creating a gui was suggested by classmate Emily Farias.
‘******************************************************
‘*** Date 10/3/17
‘******************************************************
‘*** List of changes with dates. 
* 10/14/17 added try catches
* 10/9/17 - got rid of array with actors/actresses as instructed by Dr. Woodcock
‘******************************************************
 */

public class AddBookGui extends javax.swing.JFrame {

    /**
     * Creates new form AddBookGui
     */
    //create an array list of store items
    ArrayList<StoreItem> storeItems;
    //the array is passed as an argument
    public AddBookGui(ArrayList<StoreItem> al) 
    {
        initComponents();
        storeItems = al;
        //array list is al.
       
    }
    

    private AddBookGui() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookTitle = new javax.swing.JTextField();
        bookDate = new javax.swing.JTextField();
        bookPurchasePrice = new javax.swing.JTextField();
        bookAskingPrice = new javax.swing.JTextField();
        bookAuthor = new javax.swing.JTextField();
        bookGenre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTitleActionPerformed(evt);
            }
        });

        bookDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookDateActionPerformed(evt);
            }
        });

        bookPurchasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookPurchasePriceActionPerformed(evt);
            }
        });

        bookAskingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAskingPriceActionPerformed(evt);
            }
        });

        bookAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAuthorActionPerformed(evt);
            }
        });

        bookGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookGenreActionPerformed(evt);
            }
        });

        jLabel1.setText("Title");

        jLabel2.setText("Date");

        jLabel3.setText("Purchase Price");

        jLabel4.setText("Asking Price");

        jLabel5.setText("Author");

        jLabel6.setText("Genre");

        saveBook.setText("Add Book");
        saveBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jLabel1)
                            .addGap(94, 94, 94)
                            .addComponent(bookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(89, 89, 89)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(saveBook)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bookAskingPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                    .addComponent(bookAuthor)
                                    .addComponent(bookGenre)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bookPurchasePrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(bookDate, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookAskingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(saveBook)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookTitleActionPerformed

    private void bookDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookDateActionPerformed

    private void bookPurchasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookPurchasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookPurchasePriceActionPerformed

    private void bookAskingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAskingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookAskingPriceActionPerformed

    private void bookAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookAuthorActionPerformed

    private void bookGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookGenreActionPerformed

    private void saveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBookActionPerformed
        // TODO add your handling code here:
        String title;
        String author;
        String genre;
        String Date = null;
        int purchasePrice = 0;
        int askingPrice = 0;
        
        title = bookTitle.getText();
        author = bookAuthor.getText();
       
        
        //i received the date object help from Dr. Woodcock himself on the               //website wordpress. I give full credit to Dr. Woodcock
     
        genre = bookGenre.getText();
        //purchasePrice = Integer.parseInt(bookPurchasePrice.getText());
        //askingPrice = Integer.parseInt(bookAskingPrice.getText());
        
//        //this is my try catch. it will ensure that the user will enter a number instead of words for the prices.
       //this is my try catch. it will ensure that the user will enter a number instead of words for the prices.
        try{
            purchasePrice = Integer.parseInt(bookPurchasePrice.getText());
            askingPrice = Integer.parseInt(bookAskingPrice.getText());
        
        }catch(NumberFormatException e)
        {
             JOptionPane.showMessageDialog(null, "Error for price of a movie");
        }
              
        books newBooks = new books(title, author, Date, purchasePrice, askingPrice, genre);
       //String title, String author, String dateAcquired, int purchasePrice,int askingPrice, String genre
       
       storeItems.add(newBooks);
       ObjToFile theFile = new ObjToFile();
       theFile.openFile();
       for(StoreItem item: storeItems)
       theFile.writeRecord(item);
       theFile.closeFile();
       
       //this will go back to the main GUI when the user leaves.
        mainGui mainScreen = new mainGui();
        //calling the function from the main gui
        mainScreen.updateStoreItems(storeItems);
        this.setVisible(false);
        
        mainScreen.setVisible(true);
    }//GEN-LAST:event_saveBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookAskingPrice;
    private javax.swing.JTextField bookAuthor;
    private javax.swing.JTextField bookDate;
    private javax.swing.JTextField bookGenre;
    private javax.swing.JTextField bookPurchasePrice;
    private javax.swing.JTextField bookTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton saveBook;
    // End of variables declaration//GEN-END:variables
}
