/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 *  ‘***  Class Name: addPainting
‘***  Class Author: Angelica Jones
‘******************************************************
‘*** Purpose of the class (Why did you write this class?)
‘***: for user to add items/objects/attributes for the painting class
* Creating a gui was suggested by classmate Emily Farias.
‘******************************************************
‘*** Date 10/3/17
‘******************************************************
‘*** List of changes with dates. 
* 10/14/17 added try catches
* 10/9/17 - got rid of array with actors/actresses as instructed by Dr. Woodcock
‘******************************************************
 */
 
public class AddPainting extends javax.swing.JFrame {

    /**
     * Creates new form AddPainting
     */
     //create an array list of store items
    ArrayList<StoreItem> storeItems;
    public AddPainting(ArrayList<StoreItem> al) {
        initComponents();
        storeItems = al;
        //array list is al.
    }

    private AddPainting() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        paintingDate = new javax.swing.JTextField();
        paintingTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paintingPurchasePrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        paintingHeight = new javax.swing.JTextField();
        savePainting = new javax.swing.JButton();
        paintingWidth = new javax.swing.JTextField();
        paintingAskingPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        paintingAuthor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        paintingMedia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Title");

        jLabel2.setText("Date");

        jLabel3.setText("Purchase Price");

        paintingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingDateActionPerformed(evt);
            }
        });

        paintingTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingTitleActionPerformed(evt);
            }
        });

        jLabel5.setText("Author");

        jLabel4.setText("Asking Price");

        paintingPurchasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingPurchasePriceActionPerformed(evt);
            }
        });

        jLabel7.setText("Height");

        paintingHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingHeightActionPerformed(evt);
            }
        });

        savePainting.setText("Add Painting");
        savePainting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePaintingActionPerformed(evt);
            }
        });

        paintingWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingWidthActionPerformed(evt);
            }
        });

        paintingAskingPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingAskingPriceActionPerformed(evt);
            }
        });

        jLabel8.setText("Width");

        paintingAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingAuthorActionPerformed(evt);
            }
        });

        jLabel6.setText("Media");

        paintingMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintingMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jLabel1)
                            .addGap(94, 94, 94)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(paintingHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paintingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(47, 47, 47)))
                                    .addComponent(jLabel8))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(37, 37, 37)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(paintingWidth)
                                .addComponent(paintingPurchasePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addComponent(paintingDate)
                                .addComponent(paintingAskingPrice)
                                .addComponent(paintingAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(paintingMedia))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(savePainting)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paintingTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(paintingHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paintingWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paintingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paintingPurchasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paintingAskingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(paintingMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(paintingAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(savePainting)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paintingTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintingTitleActionPerformed

    private void paintingHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintingHeightActionPerformed

    private void paintingWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintingWidthActionPerformed

    private void paintingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintingDateActionPerformed

    private void paintingPurchasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingPurchasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintingPurchasePriceActionPerformed

    private void paintingAskingPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingAskingPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintingAskingPriceActionPerformed

    private void paintingMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintingMediaActionPerformed

    private void paintingAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintingAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paintingAuthorActionPerformed

    private void savePaintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePaintingActionPerformed
        // TODO add your handling code here:
        String title;
        String author;
        String date;
        String media;
        int purchasePrice = 0;
        int askingPrice = 0;
        int height = 0;
        int width = 0;
        
        
        title = paintingTitle.getText();
        author = paintingAuthor.getText();
        date = paintingDate.getText();
        media = paintingMedia.getText();
 
        //this is my try catch. it will ensure that the user will enter a number instead of words for the prices.
        try{
          
            purchasePrice = Integer.parseInt(paintingPurchasePrice.getText());
            askingPrice = Integer.parseInt(paintingAskingPrice.getText());
        
        }catch(NumberFormatException e)
        {
             JOptionPane.showMessageDialog(null, "Error, enter a number for price");
        }
        
        
        try{
            height = Integer.parseInt(paintingHeight.getText());
            width = Integer.parseInt(paintingWidth.getText());
        }catch(NumberFormatException e)
        {
             JOptionPane.showMessageDialog(null, "Error, enter a number for height or weight");
        }
      
        
        //String title, String author, String dateAcquired, int purchasePrice, int askingPrice, int width, int height, String media
        paintings newPaintings = new paintings(title, author, date, purchasePrice, askingPrice, width, height, media);
        
        storeItems.add(newPaintings);
        
        ObjToFile theFile = new ObjToFile();
       theFile.openFile();
       for(StoreItem item: storeItems)
       theFile.writeRecord(item);
       theFile.closeFile();
        
        //this will go back to the main GUI when the user leaves.
        mainGui mainScreen = new mainGui();
        //calling the function from the main gui
        mainScreen.updateStoreItems(storeItems);
        this.setVisible(false);
        
        mainScreen.setVisible(true);
        
        
    }//GEN-LAST:event_savePaintingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPainting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPainting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPainting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPainting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPainting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField paintingAskingPrice;
    private javax.swing.JTextField paintingAuthor;
    private javax.swing.JTextField paintingDate;
    private javax.swing.JTextField paintingHeight;
    private javax.swing.JTextField paintingMedia;
    private javax.swing.JTextField paintingPurchasePrice;
    private javax.swing.JTextField paintingTitle;
    private javax.swing.JTextField paintingWidth;
    private javax.swing.JButton savePainting;
    // End of variables declaration//GEN-END:variables
}
