/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;

/**
 *
 * @author Owner
 * ******************************************************
‘***  Class Name: mainGui
‘***  Class Author: Angelica Jones
‘******************************************************
‘*** Purpose of the class (Why did you write this class?)
‘***: this is the main class, this will 
* Creating a gui was suggested by classmate Emily Farias.
‘******************************************************
‘*** Date 10/3/17
‘******************************************************
‘*** List of changes with dates. 
* 10/14/17 added try catches
* 10/9/17 - got rid of array with actors/actresses as instructed by Dr. Woodcock
‘******************************************************
 */
public class mainGui extends javax.swing.JFrame {

    /**
     * Creates new form mainGui
     */
    //Classmate Emily Farias suggested to create an Array List to store the items of the Store, haha get it?
    
   public ArrayList<StoreItem> storeItems;
    
    public mainGui() {
        initComponents();
        storeItems = new ArrayList<>();
        //create an array list
       
        
        

    }
    
   // is deserialized
    //return store item
    //add object to sttoreItems
    public StoreItem readRecord()
    {
        //create an object of store item
        StoreItem record = new  StoreItem();
         ObjectInputStream input = null;
         try
        {
            //name of the file is testFile
            input = new ObjectInputStream( new FileInputStream("testFile.txt"));
        }
        catch(IOException ioException)
        {
            System.err.println("Error opening file");
        }

        try
        {
            Object test ;
            test = input.readObject();
            String testType = test.getClass().toString();
            //find the locationn
            int loc = testType.lastIndexOf(".");
            String typename = testType.substring(loc+1);
            
            System.out.println("My type is " + typename);  
            //ensures this goes to each correct item
            
            if(typename.equals("paintings"))
            {
                record = (paintings) test;
                
            }
            else if(typename.equals("movies"))
            {
                record = (movies) test;
            }
            else
            {
                record = (books)test;
            }
            

        }
        catch (IOException ex)
        {
            System.err.println("Error writing to File");
        }
        catch (Exception ex)
        {
            System.err.println("Other error");
        }
        storeItems.add(record);
        return record; 
        //saves the items to the array
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMovie = new javax.swing.JButton();
        addBook = new javax.swing.JButton();
        addPainting = new javax.swing.JButton();
        sellView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addMovie.setText("Add Movie");
        addMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMovieActionPerformed(evt);
            }
        });

        addBook.setText("Add Book");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        addPainting.setText("Add Painting");
        addPainting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaintingActionPerformed(evt);
            }
        });

        sellView.setText("Sell/View Item");
        sellView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(sellView, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(374, 374, 374))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addPainting, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPainting, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(sellView, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMovieActionPerformed
        // this will add a movie
        AddMovie movieGui = new AddMovie(storeItems);
        this.setVisible(false);
        //makes the main screen go false
         
        movieGui.setVisible(true);
        //makes the screen visible
    }//GEN-LAST:event_addMovieActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        // this will add a book
        AddBookGui bookGui = new AddBookGui(storeItems);
        this.setVisible(false);
        
        bookGui.setVisible(true);
        //makes the screen visible
        
    }//GEN-LAST:event_addBookActionPerformed

    private void addPaintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaintingActionPerformed
        // this will add a painting
        
        AddPainting paintingGui = new AddPainting(storeItems);
        this.setVisible(false);
        
        paintingGui.setVisible(true);
    }//GEN-LAST:event_addPaintingActionPerformed

    private void sellViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellViewActionPerformed
        // This will take the user to see the informatin viewed/sold
        SellView sellViewGui= new SellView(storeItems);
        this.setVisible(false);
        
        sellViewGui.setVisible(true);
        
    }//GEN-LAST:event_sellViewActionPerformed

    //creating a method
    //set the store items array list to al
    public void updateStoreItems(ArrayList<StoreItem> al)
    
   {
       storeItems = al;
       
   }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JButton addMovie;
    private javax.swing.JButton addPainting;
    private javax.swing.JButton sellView;
    // End of variables declaration//GEN-END:variables
}
